GET http://localhost:3000/notes

###
GET http://localhost:3000/notes/64fad1c7d43b2c3710395945


###
POST http://localhost:3000/notes
Content-Type: application/json

{
    "title": "React",
    "content": "Learning all about React"
}

###
DELETE http://localhost:3000/notes


###
DELETE  http://localhost:3000/notes/64fada526d7ed0ef44e38680


###
PATCH http://localhost:3000/notes/64fad1c7d43b2c3710395945
Content-Type: application/json

{
    "title" : "Node.JS"
}

###
GET http://localhost:3000/notes/search?query=React

###
GET http://localhost:3000/notes/paginate?page=1&limit=2

###
GET http://localhost:3000/notes/paginate?page=2&limit=2

